name: Install Packages
description: Install Node.js packages

inputs:
  node-version:
    description: 'The Node.js version to use'
    required: false
    default: '20.17.0'
  working-directory:
    description: 'The working directory to run the package installation'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      id: setup-node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json

    - name: Cache NPM Dependencies
      id: cache-npm
      uses: actions/cache@v4
      with:
        path: |
          ${{ inputs.working-directory }}/node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles(format('{0}/package-lock.json', inputs.working-directory)) }}

    - name: Install Packages
      if: steps.cache-npm.outputs.cache-hit != 'true'
      shell: bash
      run: |
        npm ci
      working-directory: ${{ inputs.working-directory }}
